# baseURL = "https://no-signal.me/"
baseURL = "https://chrismade.github.io/"
languageCode = "en-us"
title = "Cogito ergo sum"
theme = "bleak"
copyright = "Chris Ma"
pygmentsCodeFences = "true"
PygmentsStyle = "perldoc"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = false
  latexDashes = true
  smartypants = false
  factions = true
  extensions = ["hardLineBreak"]

[params]
    cover = "/images/IMG_1191.jpg"
    Subtitle = "Chris's blog"
    description = "Everything is awesome !"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

